from typing import Protocol
class IPrivacyAccountant(Protocol):
    """DP会計(RDPなど)"""
    def add_mechanism(self, *, noise_multiplier:  float, steps: int = 1)->None: ...
    def get_epsilon(self, *, delta: float)->float: ...