from typing import List, Mapping, Protocol, Any
from .types import LayerId, Tensor

class ISubmodelSelector(Protocol):
    """連続層サブモデル(HE用)"""
    def make_mask(self, *, model: Any, budget_layers: int)->List[int]: ...
    def extract(self, *, model: Any, mask: List[int])->Any: ...
    def merge(self, *, full_model: Any, sub_update: Mapping[LayerId, Tensor], mask:List[int])->Any:...
